---
# tasks file for saga-verification
- hosts: all

  tasks:
    - name: Ensure the existence of the acct user
      getent:
        database: passwd
        key: acct

    - block:
        - name: Verify informix appl directory exists
          stat:
            path: /appl/
          register: application

        - name: Verify infxdata directory exists
          stat:
            path: /infxdata/
          register: informix

        - name: Verify backup directory exists
          stat:
            path: /tmp/
          register: backup

        - name: Capture Informix failures
          fail: msg="Prerequisite directory for Informix missing"
          when: not application.stat.exists or not backup.stat.exists or not informix.stat.exists

      when: database == "informix"

    - block:
        - name: Check if postgresql is installed
          command: dpkg -l postgresql
          register: check_rpm_postgresql
          ignore_errors: True

        - name: Verify /pgdata directory exists
          stat:
            path: /pgdata/
          register: pgdata

        - name: Verify /pglog directory exists
          stat:
            path: /pglog/
          register: pglog

        - name: Capture failures
          fail: msg="Prerequisite directory for postgres missing"
          when: not pgdata.stat.exists or not pglog.stat.exists or check_rpm_postgresql.stdout.find('no packages found') != -1

      when: database == "postgres"
